const fs = require('fs');
const path = 'src/App.tsx';
const lines = [
  "import { createStore, createEffect } from 'solid-js';",
  "import type { JSX } from '@solidjs/web';",
  "import './App.css';",
  "import Modal from './Modal';",
  "import InstallPrompt from './components/InstallPrompt';",
  "import { restoreState, reducer, type State, type Action } from './reducer';",
  "import { getTimestamp, setTimestamp } from './utils/idbStorage';",
  "import { useIdleDetection } from './hooks/useIdleDetection';",
  "import { usePersistedState } from './hooks/usePersistedState';",
  "import './components/InstallPrompt.css';",
  '',
  'const App = (): JSX.Element => {',
  '  const initialState: State = restoreState();',
  '  const [state, setState] = createStore<State>(initialState);',
  '',
  '  const dispatch = (action: Action) => {',
  '    setState((prev: State) => reducer(prev, action));',
  '  };',
  '',
  '  // Idle detection with persistent timestamp storage.',
  '  // The hook is storage-agnostic: it receives getTimestamp/setTimestamp',
  '  // callbacks (backed by IndexedDB) and returns a reactive idleSeconds',
  '  // accessor. onMount/onInterval dispatch to the reducer for game logic.',
  '  const { idleSeconds, setLastActive } = useIdleDetection({',
  '    getTimestamp,',
  '    setTimestamp,',
  '    onMount: (nowMs: number) => {',
  "      dispatch({ type: 'calculateIdlePoints', payload: { nowMs } });",
  '    },',
  '    onInterval: (nowMs: number) => {',
  "      dispatch({ type: 'updateTime', payload: { nowMs } });",
  '    },',
  '  });',
  '',
  '  // Open modal when idle points are available',
  '  createEffect(',
  '    () => ({ idlePoints: state.idlePoints, isModalOpen: state.isModalOpen }),',
  '    (deps: { idlePoints: number; isModalOpen: boolean }) => {',
  '      if (deps.idlePoints && !deps.isModalOpen) {',
  "        dispatch({ type: 'openModal' });",
  '      }',
  '    }',
  '  );',
  '',
  '  // Persist score and timestamp to localStorage + IndexedDB',
  '  usePersistedState(state);',
  '',
  '  const handleIncrement = () => {',
  "    dispatch({ type: 'increment' });",
  '    setLastActive();',
  "    dispatch({ type: 'updateTime', payload: { nowMs: Date.now() } });",
  '  };',
  '',
  '  const handleCloseModal = () => {',
  "    dispatch({ type: 'closeModal' });",
  "    dispatch({ type: 'awardIdlePoints', payload: { nowMs: Date.now() } });",
  '    setLastActive();',
  '  };',
  '',
  '  return (',
  '    <div class="container">',
  '      <InstallPrompt />',
  '      <h1>🧙‍♂️ Scoresceror 🧙‍♀️</h1>',
  '      <p>Press the button to increase your score!</p>',
  '      <p>✨ Score: {state.score.toLocaleString()} ✨</p>',
  '      <button onClick={handleIncrement}>🪄 Increase score! 🪄</button>',
  '      <p>🧊 Idle for: {idleSeconds()} seconds</p>',
  '      <Modal',
  '        isOpen={state.isModalOpen}',
  '        elapsedTimeMs={state.idleTimeMs || 0}',
  '        points={state.idlePoints || 0}',
  '        onClose={handleCloseModal}',
  '      />',
  '      {/* Add more components and game logic here */}',
  '    </div>',
  '  );',
  '};',
  '',
  'export default App;',
];
fs.writeFileSync(path, lines.join('\n'));
console.log('Written', lines.length, 'lines');
